# Generated by Django 2.2.6 on 2019-10-28 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAnimal', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField()),
                ('idTipoAnimal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.TipoAnimal')),
            ],
        ),
    ]
