# Generated by Django 2.2.6 on 2019-11-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20191103_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedicamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='fechaConsulta',
            field=models.DateField(null=True, verbose_name='Fecha Consulta:'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='idAnimal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Animal'),
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.AddField(
            model_name='medicacion',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Consulta'),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='medicina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Medicina'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='receta',
            field=models.ManyToManyField(through='persona.Medicacion', to='persona.Medicina'),
        ),
    ]
