# Generated by Django 2.2.6 on 2019-11-04 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20191103_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='idAnimal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Animal'),
        ),
    ]
