# Generated by Django 4.1.7 on 2023-11-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20191104_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idDueno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idTipoAnimal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.tipoanimal'),
        ),
    ]
