# Generated by Django 4.1.7 on 2023-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_animal_iddueno_alter_animal_idtipoanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
    ]
