# Generated by Django 4.1.7 on 2023-12-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_animal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idTipoAnimal',
            field=models.CharField(max_length=50),
        ),
    ]
