# Generated by Django 4.1.7 on 2023-12-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
